Portfolio: desktop version
PeacefulWiser/Portfolio-desktop-version pull request #1
Opened 2022-11-02 12:44 UTC by PeacefulWiser

2022-11-03 17:30 UTC, jerryowusu requested changes
Hi @PeacefulWiser 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, I've found some room for improvement that can help you accomplish a more readable/clean code and make your project look professional :sunglasses:

![so-close](https://user-images.githubusercontent.com/65233860/199792826-7912fc48-d4a8-42d2-9116-9076fbfa125f.gif)


## Highlights
All linters are passing :heavy_check_mark: 
Good commit messages :heavy_check_mark: 
Followed GitHub flow :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 17:30 UTC, jerryowusu commented on desktopversion.css
> +  }
Kindly check and ensure that the navigation menu list of the desktop version conforms with that of the design since there are some few differences especially in terms of alignment as indicated below. 

 Your design            |  The design template
:-------------------------:|:-------------------------:
![Screenshot from 2022-11-03 17-15-15](https://user-images.githubusercontent.com/65233860/199789633-54ff4373-93f5-4959-9fbe-510fc8278d5d.png)  |  ![Screenshot from 2022-11-03 17-05-46](https://user-images.githubusercontent.com/65233860/199789454-e5f49e88-97c1-4ac2-9b43-91c40ef6c356.png)

2022-11-03 17:30 UTC, jerryowusu commented on desktop.html
> +             </div>
There are some few disparities between your design and that of the figma. Kindly check the width and height of the languages as well as the font-weights. You can consider using a nested link where the languages, frameworks and skills will be in a list, and the sublist(JS, HTML, CSS) will be nested under languages. This will help you achieve the best work semantically as well conforming to the design.


 Your design            |  The design template
:-------------------------:|:-------------------------:
![Screenshot from 2022-11-03 17-17-24](https://user-images.githubusercontent.com/65233860/199792167-9c939d9d-3abc-4ab4-b8a5-1b311b1606db.png)  |  ![Screenshot from 2022-11-03 17-28-28](https://user-images.githubusercontent.com/65233860/199792471-6d650d86-6094-4cdb-9826-3a23559acbe2.png)

2022-11-04 07:12 UTC, Nyame-Wolf approved these changes
# STATUS: APPROVED :heavy_check_mark: :green_circle: 

Hi @PeacefulWiser  :smile: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/l4q7TIW8nEZYOJUf6/giphy.gif)


## Highlights :sparkles:
- Linters are passing
- Uses figma template

## Optional suggestions :ballot_box_with_check: 

- [ OPTIONAL] Please make the changes requested before merging. You will get to learn and in the process improve user experience for your portfolio.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

APPROVED! 💯 💯 💯

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me, @Nyame-Wolf in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 07:12 UTC, Nyame-Wolf commented on desktop.html
> +    <body>
[OPTIONAL] Good job making the chages requested though I recommend adding some more before merging. Currently your page has a scroll and provides bad user experience. I recommend matching it to the figma design
The video below highlights this:

https://user-images.githubusercontent.com/48546992/199910666-ccd1f16d-e71f-4227-b3c3-27f90e8f134d.mov

Compare with the figma design:
<img width="1433" alt="Screenshot 2022-11-04 at 09 58 26" src="https://user-images.githubusercontent.com/48546992/199911106-89580939-d6e9-44b7-b571-4af74f3a361b.png">
Your page should fill the entire screen just as the figma design.

2022-11-04 07:12 UTC, Nyame-Wolf commented on desktop.html
> +        </section>
[OPTIONAL] Kindly not that the layout of the page should have five sections:
`header` with the navbar use `display:flex`
`<section>` headline use `display:flex`
`<section>` works use `display: grid` on section and `display:flex` to align cards/articles
`<section>`about use `display:flex`
`<section>` or `<footer>` contact form use `display:flex`

As per the previous [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md), you were required to have your works section being one container for all the items. This section was to use grid to layout these items. The items themselves were to use flexbox to align 

Currently you have the items using `display:grid` and no `display:flex` in your project.
Kindly fix these to match [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md).

2022-11-04 08:53 UTC, merged